name: Run Tests on Master

on:
  schedule:
  - cron: "30 5 * * 1"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 18
      name: Set up Node.js

    - name: Change directory to js/
      run: cd js

    - run: npm ci
    - run: npm test
