name: Run Tests on Master

on:
  schedule:
  - cron: "30 5 * * 1"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
      name: Set up Node.js

    - run: npm ci
      working-directory: ./js
      
    - run: npm test
      working-directory: ./js
        
