name: Run Tests on Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'latest'

    - name: Change directory to js/
      run: cd js

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
